### ISSUE TITLE
Info coming soon?

### ISSUE THREAD

**Issue by endrebak** [snakemake-days/snakemake-days.github.io#1]
We are several people who would like to come from abroad. Therefore we would like to plan and buy plane tickets ahead of time.

Is it only the 15. or will there be more days/coding sessions etc. for those who are extra interested? Who will it be interesting for etc - both newbs and advanced Snakemakers?

Endre

**Comment by johanneskoester** [comment]
Glad to hear that! @mgalland wants to add some details soon. I am not so much involved in the organization, but I will let you know once I know more.

**Comment by mgalland** [comment]
Hey Endre, 
The workshop will only last one day (December 15th) so there are no specific coding sessions whatsoever planned so far. Could be an idea to make it a two day event in the future. 

I am currently setting up a Data Carpentry workshop on Genomics on December 13-14th. Would that be of interest for you?

I've made a tentative program [here](https://github.com/snakemake-days/snakemake-days.github.io/blob/master/_posts/2017-10-20_scientific_and_organisation_committee.md).

**Comment by johanneskoester** [comment]
@endrebak there will be a hackathon in the afternoon, were people can present problems and we can discuss solutions together.

**Comment by endrebak** [comment]
I signed up and so did a colleague :)

Thanks 👍

**Comment by mgalland** [comment]
Dear @endrebak 
I have recently contacted some people from the Software/data Carpentry organisation to organise a workshop on genomics (basic level).  
You can have a peek at the lessons [here](http://www.datacarpentry.org/genomics-workshop/) but the lesson will be soon updated. 
This workshop will take place on December 13-14 also in Amsterdam (same campus as the Snakemake day, Roeterseiland campus, room E0.15).
Is that of interest to you?

**Comment by endrebak** [comment]
Thanks for the heads-up but it seems like I know some of it already :)
